### ISSUE TITLE
train model

### ISSUE THREAD

**Issue by amirtaherkhani** [tamarakatic/sentiment-analysis-in-amazon-reviews#9]
how to can train the models ? please help me for train dnn models tanx

**Comment by tamarakatic** [comment]
It is explained here: 
https://github.com/tamarakatic/sentiment-analysis-in-amazon-reviews/blob/master/README.md#deep-learning-models
But first, install all dependencies and process dataset: 
https://github.com/tamarakatic/sentiment-analysis-in-amazon-reviews/blob/master/README.md#installing

If you have any questions please let me know!
